### ISSUE TITLE
Create a landing page about what the project stands for and how to go about with the project

### ISSUE THREAD

**Issue by karthiknadar1204** [tusharzalte/tusharesume#1]
We need to create a landing page that entails the process being used to create the resume and how would a resume builder be beneficial to the user to get the user started

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by adityavpawar** [comment]
I would like to work on this issue under gssoc'23

**Comment by ZapeeoSheikh** [comment]
@karthiknadar1204 Issue has been assigned you 👍🏻

**Comment by karthiknadar1204** [comment]
Please check pr #58 , that was my pr but still hasn't been given any kind of label @ZapeeoSheikh @tusharzalte

**Comment by karthiknadar1204** [comment]
Also please add a gssoc label to this issue

**Comment by karthiknadar1204** [comment]
@ZapeeoSheikh I can't start working on any issue unless labels for gssoc and levels are put up.
Please look into it.
@tusharzalte
