### ISSUE TITLE
Dependencies, Browserlists, Proxies and Orientation issues of Resume Builder Form

### ISSUE THREAD

**Issue by rks-031** [tusharzalte/tusharesume#102]
### Description

The project has various **warnings** and **errors** due to **deprecated dependencies**, **outdated browserlists**, **proxy errors**, **bad orientation of project components** as described below:

**Issue 1.**
![res-1](https://github.com/tusharzalte/tusharesume/assets/103258259/3eae74c2-302e-4635-b4ef-f72283a187f6)

The warnings shown above suggest that some of the packages used in the project are **deprecated** or no longer **actively maintained**.

This issue can be addressed by simply running the command: **npm update stable** on the terminal.

 

**Issue 2.**
![res-2](https://github.com/tusharzalte/tusharesume/assets/103258259/7cdfc6e1-bf0d-4fd7-b3a6-f4545cf4bfb2)

The warning message received indicates that the **caniuse-lite** package used by Browserslist is outdated.

To address this warning and update caniuse-lite, we can follow these steps:

->Open a terminal or command prompt.

->Navigate to the root directory of your project:

->Run the following command to update caniuse-lite:

**npx browserslist@latest --update-db**

This command uses the npx tool to execute the latest version of browserslist and update the browser support database (caniuse-lite).

After running the command, we will be able to see the  output indicating that the database has been updated.
Now, when we compile your project, we no longer see the warning related to caniuse-lite being outdated.

![res-corr-1](https://github.com/tusharzalte/tusharesume/assets/103258259/e941434c-757a-46a9-a6ce-cd55f7cf8765)

**Issue 3.**
![res-3](https://github.com/tusharzalte/tusharesume/assets/103258259/9e92a4a9-df1a-4ae7-8bde-e65175c46d19)

The proxy errors are occuring  as there is a **misconfiguration or conflict** with the **proxy** settings in the project.

![res-5](https://github.com/tusharzalte/tusharesume/assets/103258259/a790fa31-ecc0-4ef0-8def-d6029c3024e5)

**Issue 4.**
![form shifting](https://github.com/tusharzalte/tusharesume/assets/103258259/aa4bc632-7ee0-4000-9306-7c1dd23e0a82)

The homepage of the resume builder form is highly **disoriented** and can leave a negative impact on the users about the website.

A few **css properties** can be correct to fix this issue such as : giving a style tag of **marginTop** under the form tag in the **Login.js** file, altering the **top and font-size** values under **brand** class of **authentication.css** file imported by Login.js and altering the **padding-bottom and font-size** values under **footer** class of **footer.css** file imported by Footer.js.

![form-margin](https://github.com/tusharzalte/tusharesume/assets/103258259/cf5458e0-0480-4a09-bc1f-caa53b5a7b1f)

![footer css](https://github.com/tusharzalte/tusharesume/assets/103258259/7fbeaf03-591c-40c7-9ff4-d5de01e29cff)

![authentication css](https://github.com/tusharzalte/tusharesume/assets/103258259/aa94255d-c704-490a-8e47-42993bbd9ed9)

**Here's how the page will look after correction:**

![perfect](https://github.com/tusharzalte/tusharesume/assets/103258259/e007a5f2-b45b-496d-a33f-14411dc76bef)

**Issue 5.**
![register](https://github.com/tusharzalte/tusharesume/assets/103258259/af589902-6cbc-4958-b2d4-5bf7bfebd9de)

The function in the **Login.js** file under the **Pages/src** should be named **conventionally** as **Login()** instead of **Register()**.
This will maintain uniformity in the program as per the **ReactJS** norms.

![login correct](https://github.com/tusharzalte/tusharesume/assets/103258259/6736878f-913c-4eaf-89bf-386d284e22e8)

#

### Additional information

The above mentioned **issues/bugs** need to be addressed so as to ensure efficient and smooth functioning of this project. Thus,  I would request you to kindly **assign** me the task to work on these issues.

**Comment by ZapeeoSheikh** [comment]
Thanks for contributing !!
PR has been merged
