### ISSUE TITLE
Fixing the design of login page.

### ISSUE THREAD

**Issue by riyagupta2011** [tusharzalte/tusharesume#106]
### Description

The login and registration page has a design issue where Resume Builder is not visible.

Please assign me this issue under GSSOC'23.

### Screenshots

![Screenshot (367)](https://github.com/tusharzalte/tusharesume/assets/98754072/15752c66-1a3a-4ee6-a48d-ce3deb0f16fc)

**Comment by Snigdha2712** [comment]
Please assign this project to me. i will fix the issue

**Comment by ZapeeoSheikh** [comment]
Issue has been resolved !
