### ISSUE TITLE
Captcha is not working 

### ISSUE THREAD

**Issue by ZapeeoSheikh** [tusharzalte/tusharesume#132]
### Description

Debug the web app and fix the captcha as it is not working

**Comment by debsouryadatta** [comment]
I am working on it, please assign me this issue

**Comment by aryan-bhokare** [comment]
I faced the same issue make, I changed the proxy which was default on 5000 to the port on which I ran server.js and the captcha issue resolved.

**Comment by tusharzalte** [comment]
can i assigned you this issue?
