### ISSUE TITLE
[FEATURE] Add show/hide password feature

### ISSUE THREAD

**Issue by Avinash905** [tusharzalte/tusharesume#151]
### Description

- The purpose of the show/hide password feature is to provide users with the flexibility to verify the accuracy of their input or ensure that they have entered the correct password without the risk of someone else seeing it. 
- It can be especially helpful in scenarios where users may have made a mistake while typing their password or when they want to double-check if they have entered it correctly.

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by sagarb2003** [comment]
Hey @ZapeeoSheikh Please assign me  this issue under GSSOC'23

**Comment by agarwalhimanshugaya** [comment]
i want to work on this issue please assign to me
