### ISSUE TITLE
Allow me to change the Update profile Page

### ISSUE THREAD

**Issue by Rupantar-Borphukan** [tusharzalte/tusharesume#16]
It looks like a basic form having different input like mail, phone, linkedin account etc.
But we can build good UI.

![profile](https://github.com/tusharzalte/tusharesume/assets/94108574/304968eb-4503-4593-9dd5-fa5a52470e65)

Please assign me to change the page especially the UI part and more info can be taken from user to the profile section. Second Important point - there is nothing like sign up with google or facebook like that. We can use that as it can save time of user and all data can be fetch from google from user. (We can use google authentication in the website)

**Comment by tusharzalte** [comment]
okay done

**Comment by tusharzalte** [comment]
okay done

**Comment by Rupantar-Borphukan** [comment]
> okay done

Please assign me the issue so that I can solve that.

**Comment by tusharzalte** [comment]
how i assigned you?
