### ISSUE TITLE
Add error handling middleware to server.js

### ISSUE THREAD

**Issue by sagnik3788** [tusharzalte/tusharesume#17]
I want to work on this issue @tusharzalte

**Comment by madhur87** [comment]
I would love to assist if there be any need for assistance @sagnik3788 @tusharzalte

**Comment by sagnik3788** [comment]
@madhur87 sure

**Comment by Ujala-2110** [comment]
I want to work on this issue @tusharzalte ,please assign it to me,
Thank u
