### ISSUE TITLE
Add Password Bcrypt Functionality 

### ISSUE THREAD

**Issue by madhur87** [tusharzalte/tusharesume#24]
Store Password as a Hashing String.

Please Assign me @tusharzalte

**Comment by vikashjalandra** [comment]
Describing the issue
Add Encrypt password functionality

Solution
I can add password encryption by the bcrypt.js library.

Additional
I can also add encrypted authentication on login.

Please let me know if I can add something more to this idea.
Thank you

**Comment by jessicacb12** [comment]
I agree with this @tusharzalte. Please assign this issue either to @madhur87 or @vikashjalandra

**Comment by tusharzalte** [comment]
Okay

**Comment by tusharzalte** [comment]
> I agree with this @tusharzalte. Please assign this issue either to @madhur87 or @vikashjalandra

I assigned
