### ISSUE TITLE
Add JWT Middleware

### ISSUE THREAD

**Issue by madhur87** [tusharzalte/tusharesume#25]
Impalement API Secure JWT Authenticate.

Please assign me! @tusharzalte

**Comment by madhur87** [comment]
Can you assign @tusharzalte

**Comment by tusharzalte** [comment]
okay

**Comment by tusharzalte** [comment]
i assign you

**Comment by vaibhav0726** [comment]
Hey @madhur87! Any update on this. I want to work on this.

**Comment by madhur87** [comment]
Yeh almost done, today I create a MR
