### ISSUE TITLE
Apply with linkedin

### ISSUE THREAD

**Issue by jessicacb12** [tusharzalte/tusharesume#27]
Greetings @tusharzalte! This would be challenging for me but if user can parse their LinkedIn profile to autofill the resume I believe it would be awesome! So the flow would be like:

1. User choose the template
2. There's a button above the form with something like Autofill with LinkedIn
3. After clicking the button, we'll try to scrape the LinkedIn with lib like cheerio
4. Autofill the form based on the acquired data

Let me know what you think and once you agree, please assign this issue to me. Thanks!

**Comment by tusharzalte** [comment]
Yess sure

**Comment by jessicacb12** [comment]
@tusharzalte please assign this issue to me so I can start working on this

**Comment by tusharzalte** [comment]
Can you please tell me how I assign you?

**Comment by jessicacb12** [comment]
You can add assignee at the top right sider as mentioned in https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users

**Comment by tusharzalte** [comment]
Check it once

**Comment by jessicacb12** [comment]
ok thanks!

**Comment by tusharzalte** [comment]
can you deploy this project?

**Comment by jessicacb12** [comment]
@tusharzalte well I have ever deployed my personal project to vercel 😂 it's convenient. Every new commit will trigger redeployment

**Comment by tusharzalte** [comment]
Ohhhh

**Comment by tusharzalte** [comment]
So are you deploying project or not?

**Comment by jessicacb12** [comment]
You want me to deploy this project to vercel? If you want I can create a new issue for that

**Comment by tusharzalte** [comment]
Yes

**Comment by tusharzalte** [comment]
> @tusharzalte please assign this issue to me so I can start working on this

have you add the feature that you mentioned?

**Comment by jessicacb12** [comment]
Sorry I will start exploring this at weekend

**Comment by tusharzalte** [comment]
Okay
