### ISSUE TITLE
Restructure the Code to follow MVC architecture.

### ISSUE THREAD

**Issue by Preetam078** [tusharzalte/tusharesume#28]
Hello @tusharzalte I want to change the project backend structure to follow the MVC (Model View Controller) pattern, I will a seperate Route file consisting all the Route of the APIs and a different Service File having the real backend code which execute of hitting the APIs. This will help to make the backend more scalable. 

Please assign this Issue to me under Gssoc 2023

**Comment by Preetam078** [comment]
Hello sir please assign this issue to me so that I can start coding.

**Comment by ZapeeoSheikh** [comment]
Already assigned above
