### ISSUE TITLE
Change class to className

### ISSUE THREAD

**Issue by Avinash905** [tusharzalte/tusharesume#29]
![Screenshot (421)](https://github.com/tusharzalte/tusharesume/assets/56786344/5959a254-2f0d-4e6d-920d-7f0aa5a1e54a)

There is an error message showing up in the console tab because of the **class** instead of **className** in the Footer.js file.

Please assign me this issue so that I can resolve it under **GSSOC'23**

**Comment by vikashjalandra** [comment]
Describing the issue
Change class to className

Solution
I will change all classes with className.

Additional
I can also redesign the sign-up and login pages.

Please let me know if I can add something more to this idea.
Thank you

**Comment by ZapeeoSheikh** [comment]
Issue has been assigned you 👍🏻

**Comment by Avinash905** [comment]
@ZapeeoSheikh I have asked to assign the issue to me first so can you please assign it to me

**Comment by ZapeeoSheikh** [comment]
Issue has been assigned you 👍
