### ISSUE TITLE
Adding .env file. 

### ISSUE THREAD

**Issue by vaibhav-xt** [tusharzalte/tusharesume#3]
I am GSSOC'S 2023 CONTRIBUTOR

It's what I think is most important to have because It reveals the credentials of the user also It's good practice for production-level code.

![Screenshot (407)](https://github.com/tusharzalte/tusharesume/assets/90946899/ca7886b8-f75a-4252-a74c-7eeb9ee91fd1)

## Note: I would like to work on this issue.

**Comment by AKsHaT123456A** [comment]
Hi @tusharzalte can you assign me this issue?

**Comment by JainPriya1234** [comment]
I would like to work on this issue

**Comment by aniket2125ec1117** [comment]
I am GSSOC 23 contributer and i love to work on this project
