### ISSUE TITLE
Home page is not responsive

### ISSUE THREAD

**Issue by Avinash905** [tusharzalte/tusharesume#32]
![Screenshot (424)](https://github.com/tusharzalte/tusharesume/assets/56786344/408c21a1-41ec-49d6-9b89-907517fd0353)

The home page is not responsive.

Please assign me this issue so that I can resolve it under **GSSOC'23**

**Comment by ZapeeoSheikh** [comment]
Assigned

**Comment by Avinash905** [comment]
Can you please add **GSSoC'23** label and **level** label to this issue?
