### ISSUE TITLE
Add ContributingGuidelines.md

### ISSUE THREAD

**Issue by shanvijha30** [tusharzalte/tusharesume#35]
The Contributing Guideline documentation will contain set of guidelines that will help contributors during the contribution process.
File type markdown.

**Comment by shanvijha30** [comment]
@tusharzalte could you please assign this issue to me.
Thank you!

**Comment by shanvijha30** [comment]
@tusharzalte Could you please assign this issue to me.

**Comment by ZapeeoSheikh** [comment]
Resolved
