### ISSUE TITLE
Add animations to different buttons 

### ISSUE THREAD

**Issue by silwite** [tusharzalte/tusharesume#37]

**Comment by silwite** [comment]
@tusharzalte I'm not able to register its giving proxy error and registration failed , if you could help me in this

**Comment by tusharzalte** [comment]
How I help you but?

**Comment by tusharzalte** [comment]
Okay

**Comment by silwite** [comment]
I have added .please do check . GSSOC'23

**Comment by tusharzalte** [comment]
Any update?

**Comment by silwite** [comment]
I have added a PR already

**Comment by tusharzalte** [comment]
Okay
