### ISSUE TITLE
Deploy the resume builder

### ISSUE THREAD

**Issue by Avinash905** [tusharzalte/tusharesume#39]
Please assign it to me so that I could deploy the project under **GSSOC'23**.

**Comment by jessicacb12** [comment]
@Avinash905 will you use web hosting like vercel?

**Comment by jessicacb12** [comment]
@tusharzalte then following our discussion in https://github.com/tusharzalte/tusharesume/issues/27, then you can assign this issue to @Avinash905

**Comment by tusharzalte** [comment]
> 👍👍

any update?

**Comment by komalioruganti** [comment]
I will deploy the backend by today and update you

**Comment by tusharzalte** [comment]
Great, thanks for the update.

**Comment by komalioruganti** [comment]
I deployed it. Here is the link: https://tusharesume.onrender.com/
The repository connected to this deployment is https://github.com/komalioruganti/tusharesume-backend
And the frontend is deployed on netlify using the github repository:
https://github.com/komalioruganti/tusharesume-frontend

**Comment by komalioruganti** [comment]
The backend is deployed using render by the way

**Comment by komalioruganti** [comment]
In the frontend or backend?

**Comment by tusharzalte** [comment]
In backend

**Comment by tusharzalte** [comment]
have you seen that?

**Comment by komalioruganti** [comment]
Yeah I did. I don't know why that's happening. I think maybe the data from MongoDB is not being rendered properly or something.

**Comment by tusharzalte** [comment]
can we both work on that?
