### ISSUE TITLE
Installation Guide to Readme.md

### ISSUE THREAD

**Issue by vaibhav-xt** [tusharzalte/tusharesume#4]
No installation guide to this readme.md

Assign to me please.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by sujitmemane** [comment]
Hello, Sir! 👋🏼

I am [Sujit Memane](https://thesujitmemane.vercel.app/), a front-end React developer with expertise in creating visually stunning user interfaces. I have a strong portfolio that showcases my past work, highlighting my skills and abilities in designing attractive UIs.

I would be thrilled to contribute to the Readme.MD, Please assign this to me 

Looking forward to the opportunity!

Porrtfolio Link : https://thesujitmemane.vercel.app/
Recent Project : https://bummer-eight.vercel.app/
