### ISSUE TITLE
Restructure the server to MVC [GSSOC23]

### ISSUE THREAD

**Issue by bemoierian** [tusharzalte/tusharesume#44]
Restructure the server to the Model-View-Controller to achieve SoC and better maintainability.

**Comment by tusharv01** [comment]
HI, @bemoierian please assigned me with this issue as my skills are aligned for solving this issue.

**Comment by Preetam078** [comment]
hi author and admin i have already raised the issue previously on
 Restructure the Code to follow MVC architecture. #28

please assign this issue to me. thank you.

**Comment by ZapeeoSheikh** [comment]
@Preetam078  Issue has been assigned you 👍🏻

**Comment by madhur87** [comment]
Hi @Preetam078, I have already fix this Issue [MR Link](https://github.com/tusharzalte/tusharesume/pull/80) 

@ZapeeoSheikh, its good be close this issue.

**Comment by Preetam078** [comment]
@madhur87  i went through your code, you tried to make the MVC codebase but i can add more scalability to the code by separating the routes and the respective and functions called by the http request. please don't close this issue i will rise the PR in this weekend
