### ISSUE TITLE
Correct the readme

### ISSUE THREAD

**Issue by karthiknadar1204** [tusharzalte/tusharesume#48]
Right now it tells the user to navigate to client folder via cd client but in the codebase ,it is named client1

**Comment by karthiknadar1204** [comment]
I would like to work on this issue inder gssoc'23

**Comment by tusharzalte** [comment]
okay can you deploy frontend and backend as well?

**Comment by karthiknadar1204** [comment]
Its just a readme file fix so i dont think i have to deploy it
Can i work on it

**Comment by tusharzalte** [comment]
yes please

**Comment by ZapeeoSheikh** [comment]
Resolved

**Comment by karthiknadar1204** [comment]
@ZapeeoSheikh Please add gssoc label to the issue and level to the pr made
