### ISSUE TITLE
Improve UI and increase backend Functionalities 

### ISSUE THREAD

**Issue by RazzaqShikalgar** [tusharzalte/tusharesume#5]
We can add **AI to auto generate bio or content based on given keywords** so our resume gets more strong and also will try to autogenerate templates of template 
Please assign me this issue I'll try maximum side of backend and will add AI for text generation and try to do template wala thing

**Comment by SHIVA769** [comment]
I  would like  this project .please assign

**Comment by ZapeeoSheikh** [comment]
@RazzaqShikalgar You have been assigned this issue

**Comment by SHIVA769** [comment]
Yes
