### ISSUE TITLE
[Feature][GSSOC23]: Missing Form Labels in every sections

### ISSUE THREAD

**Issue by ayushkumarbhadani** [tusharzalte/tusharesume#54]
Hey @tusharzalte, Need to add the form labels in every section so that there is no confusion about the data which needs to be entered.

<img width="812" alt="Screenshot 2023-05-26 at 8 44 07 AM" src="https://github.com/tusharzalte/tusharesume/assets/73775939/26375f3f-c85c-4cb3-8504-418182665693">

Assign this issue to me under the GSSOC23 label.

**Comment by ZapeeoSheikh** [comment]
Issue has been assigned you 👍🏻

**Comment by ayushkumarbhadani** [comment]
Hey @ZapeeoSheikh, kindly review PR #85 and merge it to the main.

**Comment by ayushkumarbhadani** [comment]
Closing this issue as it's been merged!
