### ISSUE TITLE
Add environmental file. 

### ISSUE THREAD

**Issue by Soura700** [tusharzalte/tusharesume#6]
Want to contribute to the project in backend

**Comment by AKsHaT123456A** [comment]
@tusharzalte can you assign me this ?

**Comment by NullCoder11** [comment]
Hello sir, I am a GSSOC'23 Contributer. Can you please assign me this task?

**Comment by Uma-Shankar0927** [comment]
I would like to handle this issue. To go through all sensitive data and add them to the .env file. Please assign this task to me. Thank You.
