### ISSUE TITLE
dropdown for every field like degree year 

### ISSUE THREAD

**Issue by shravan-das** [tusharzalte/tusharesume#62]
i would like to add a feature of dropdown in every possible dropdown field like qualification, year..etc in education field.
i would like to get assigned to this task
under GSSOC'23
![Screenshot (97)](https://github.com/tusharzalte/tusharesume/assets/100745475/ffa9b5e5-5e4c-4c27-bc47-093a4b862c63)

**Comment by tusharzalte** [comment]
okay i assign you

**Comment by ZapeeoSheikh** [comment]
Merged Closed ⭐️

**Comment by shravan-das** [comment]
@ZapeeoSheikh please assign gssoc label to it because pull requests are not counted if you dont do so :(

**Comment by shravan-das** [comment]
thank you very much sir!, very much appreciated
