### ISSUE TITLE
Add CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by parthpathakpp1** [tusharzalte/tusharesume#64]
There should be a Code of Conduct . Which will give guidelines to the conributors .

**Comment by parthpathakpp1** [comment]
Assign this issue to me under GSSOC'23.

**Comment by ZapeeoSheikh** [comment]
@parthpathakpp1  Issue has been Assigned you 👍🏻

**Comment by ZapeeoSheikh** [comment]
Merged Closed ⭐️
