### ISSUE TITLE
[GSSOC'23] add a feature of comment in the resume

### ISSUE THREAD

**Issue by vivxsdb** [tusharzalte/tusharesume#68]
I want to create a feature that allows users to make their resumes public on the platform, enabling others to provide feedback and suggestions for improvement. This will be especially helpful for beginners who can use it as a reference to create their own resumes.
Can u assign this feature under GSSOC'23

**Comment by vivxsdb** [comment]
can i get 4-5 days time extra to complete this project . i am very much interesed in doing this project

**Comment by vivxsdb** [comment]
Actually due to my sem exam the project is taking some time And I have built the backend part also I can show you my work also untill now what I did . give me a few days time extra  to complete this

**Comment by ZapeeoSheikh** [comment]
Sure you can take time.
