### ISSUE TITLE
Add new resume templates

### ISSUE THREAD

**Issue by shwetasharma10** [tusharzalte/tusharesume#7]
Please assign this issue to me as a part of GSSOC'23

**Comment by adityavpawar** [comment]
Please assign this issue to me as a part of GSSOC'23

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by SiennaBrook** [comment]
I want to work on this issue, please assign me this task as a part of GSSOC'23

**Comment by Vanshika1021** [comment]
I want to work on this please assign me this issue.
