### ISSUE TITLE
MVC structure setup

### ISSUE THREAD

**Issue by lovetyagi-17** [tusharzalte/tusharesume#71]
### Description:

This pull request proposes the implementation of the Model-View-Controller (MVC) design pattern in the resume builder project. The current codebase lacks a clear separation of concerns, leading to potential difficulties in maintaining and extending the application. By introducing MVC architecture, we aim to improve the code organization, enhance code reusability, and make future development and maintenance more efficient.

### Proposed Changes:

    Model: Create a dedicated model file to represent the data structure and logic of a resume. This model will encapsulate resume-related properties, such as personal information, education, work experience, skills, and other relevant sections.

    View: Develop a separate view component responsible for rendering the resume template and capturing user inputs. The view will provide an intuitive user interface to customize and preview the resume.

    Controller: Implement a controller component to handle user actions and orchestrate the flow of data between the model and view. The controller will process user inputs, update the model accordingly, and coordinate the rendering of the updated resume in the view.

    Refactor Existing Code: Modify the existing codebase to align with the MVC architecture. Extract relevant code sections into the appropriate model, view, and controller components, ensuring clear separation of concerns.

### Objective:

By implementing the MVC pattern in the resume builder project, we aim to achieve a more modular, maintainable, and extensible codebase. This enhancement will improve code organization, promote reusability, and simplify future development and maintenance efforts.

**Comment by lovetyagi-17** [comment]
please assign this issue to me under **GSOC-2023** tag.
Happy to start working on this.

**Comment by ZapeeoSheikh** [comment]
@lovetyagi-17 Issue has been assigned you 👍🏻
