### ISSUE TITLE
[FEATURE] Add greeting bot

### ISSUE THREAD

**Issue by k-deepak04** [tusharzalte/tusharesume#91]
### Description

"By adding a greeting bot that acknowledges and appreciates pull requests, we can create a positive and motivating environment for contributors."

"The greeting bot's personalized message will make contributors feel valued and encourage them to continue their great work."

"Having a greeting bot in place ensures that contributors receive immediate recognition and assurance that their contributions are being reviewed and appreciated."

### Screenshots

![image](https://github.com/tusharzalte/tusharesume/assets/96341431/fea29034-e4ba-4ff4-ba98-81a513fd6d73)

### Additional information

Assign this to me under GSSOC'23 :)

**Comment by ZapeeoSheikh** [comment]
Issue has been assigned you.

**Comment by k-deepak04** [comment]
Creating a PR shortly :)

**Comment by k-deepak04** [comment]
#100 PR filed
