### ISSUE TITLE
Redesigning the website using Figma. [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [tusharzalte/tusharesume#96]
### Description

The design of the website looks very basic and unprofessional. I can improve the design using using Figma. Here are some sample homepages and components:

### Screenshots

![homepage for issue](https://github.com/tusharzalte/tusharesume/assets/116020663/d3cdc05b-3969-4765-853a-4987b5a274f7)
![buttons design](https://github.com/tusharzalte/tusharesume/assets/116020663/226fe924-ea38-4ed7-88f6-97065a3eb764)
![designcard](https://github.com/tusharzalte/tusharesume/assets/116020663/b74c6eff-b6d7-45b1-8455-7f5607d72057)

### Additional information

Please assign me this issue under GSSoC'23

**Comment by ZapeeoSheikh** [comment]
@1Shubham7 will you only redesign it in figma or also work on codebase to improve the design ?

**Comment by 1Shubham7** [comment]
@ZapeeoSheikh I will do both. Design it on Figma. Send you the design and then code it on the website.
