### ISSUE TITLE
[FEATURE] Navigating the user to the homepage after registration

### ISSUE THREAD

**Issue by pshantanu771** [tusharzalte/tusharesume#97]
### Description

After registering on the website it just clears the form and shows registration successful and then we have to re-login.
Instead I'll redirect the user directly to the homepage after successfull registration instead of making him re-login. This will improve the UX

Please assign me this issue under GSSOC'23

**Comment by Visbhavesh** [comment]
Please assign me.

**Comment by ZapeeoSheikh** [comment]
@pshantanu771 Issue has been assigned you.

**Comment by pshantanu771** [comment]
> @pshantanu771 Issue has been assigned you.

Opened the pull request. Please review and merge if all seems good
